In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,2,3,],[4,5,6]])
new=arr.ravel()
new[0]=200
new

array([200,   2,   3,   4,   5,   6])

In [ ]:
arr

array([[200,   2,   3],
       [  4,   5,   6]])

In [ ]:
new2=arr.flatten()
new2[1]=200
new2

array([200, 200,   3,   4,   5,   6])

In [ ]:
arr

array([[200,   2,   3],
       [  4,   5,   6]])

In [ ]:
print(np.sqrt(arr))

[[14.14213562  1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974]]


In [ ]:
print(np.exp(2))

7.38905609893065


In [ ]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [ ]:
a=np.array([1,2])
b=np.array([3,4])

In [ ]:
print(a*b)

[3 8]


In [ ]:
print(a+b)

[4 6]


In [ ]:
print(a**2)

[1 4]


In [ ]:
arr=np.array([1,2,3,4,5,6])

In [ ]:
arr[-1:-4:-1]

array([6, 5, 4])

In [ ]:
arr=np.array([[1,2,3,],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[0:3:,0:4:2]

array([[1, 3],
       [4, 6]])

In [ ]:
ind=[[0,1],[2,3],[4,5]]
n=np.take(arr,ind)
n

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
new=arr.reshape(3,2)
new

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
for i in np.nditer(arr):
    print(i,end=" ")

1 2 3 4 5 6 

In [ ]:
for ind,i in np.ndenumerate(arr):
  print(ind,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [ ]:
arr=np.array([1,2,3,4,5])
new=arr[1:3].copy()
new[0]=100
new

array([100,   3])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr=np.array([1,2,3,4,5])
new=arr[1:3]
new[0]=100
new

array([100,   3])

In [ ]:
arr

array([  1, 100,   3,   4,   5])

In [ ]:
arr=np.array([[1,2,3,],[4,5,6]])
print(arr.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr.shape

(2, 3)

In [ ]:
n=np.repeat(arr,2)
print(n)
print(arr)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
f=np.tile(arr,2)
f

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
sum=np.sum(arr)
sum

np.int64(21)

In [ ]:
s=np.sum(arr,axis=1)
s

array([ 6, 15])

In [ ]:
arr=np.array([1,2,3])
res=np.logical_or(arr>0,arr<2)
res

array([ True,  True,  True])

In [ ]:
a=np.array([1,2,3])
b=4
a+b

array([5, 6, 7])

In [ ]:
a=np.array([[1,2,3]])
b=np.array([[5],[6],[7]])
a+b

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

In [ ]:
a=np.array([1,2,3])
a**2

array([1, 4, 9])

In [ ]:
def square(x):
  return x*x
vfun=np.vectorize(square)
a=np.array([1,2,3])
vfun(a)

array([1, 4, 9])

In [ ]:
a=np.array([1,np.nan,3])
print(np.isfinite(a))

[ True False  True]
